language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gaurav4741/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gaurav4741/react-test npm test

after_success:
  - docker build -t gaurav4741/multi-client ./client
  - docker build -t gaurav4741/multi-nginx ./nginx
  - docker build -t gaurav4741/multi-server ./server
  - docker build -t gaurav4741/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gaurav4741/multi-client
  - docker push gaurav4741/multi-nginx
  - docker push gaurav4741/multi-server
  - docker push gaurav4741/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-719541647392"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
