language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gaurav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gaurav/react-test npm test

after_success:
  - docker build -t gaurav/multi-client ./client
  - docker build -t gaurav/multi-nginx ./nginx
  - docker build -t gaurav/multi-server ./server
  - docker build -t gaurav/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gaurav/multi-client
  - docker push gaurav/multi-nginx
  - docker push gaurav/multi-server
  - docker push gaurav/multi-worker
