sudo: required
services:
  - docker

before_install:
  - docker build -t gaurav/rect-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gaurav/react-test npm test -- --coverage

after_success:
  - docker build -t gaurav/multi-client ./client
  - docker build -t gaurav/multi-nginx ./nginx
  - docker build -t gaurav/multi-server ./server
  - docker build -t gaurav/multi-worker ./worker
