version: '3'
services:
  client:
    image: 'gaurav4741/multi-client'
    hostname: client
  server:
    image: 'gaurav4741/multi-server'
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATBASE=$PGDATBASE
      - PGPASSWORDS=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'gaurav4741/multi-worker'
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'gaurav4741/multi-nginx'
    hostname: nginx
    ports:
      - "80:80"
